### ISSUE TITLE
Green color inside the text

### ISSUE THREAD

**Issue by aha999** [stefan-niedermann/paypal-donate-button#2]
I think that the green color inside the text doesn't look so good, awesome button tho:

![slika](https://user-images.githubusercontent.com/50620416/72663010-f2195400-39ed-11ea-93be-56b663787490.png)

**Comment by stefan-niedermann** [comment]
Thank You 😆 

Well, it is supposed to be white, but i guess Gimp (or JPG?) did mess it up because the line is too thin to be rendered clearly. I'll have a look when i have some time :)

**Comment by stefan-niedermann** [comment]
Fixed in 20bd2a36ba6580437d12743229f6b09e1b29433d

![New version](https://raw.githubusercontent.com/stefan-niedermann/paypal-donate-button/master/paypal-donate-button.png)

You might need to clear your cache to see the new version.
